---
#- name: 1.system initialization
#  gather_facts: false
#  hosts: all
#  roles: 
#    - common
#  tags: common

#- name: 2.Signed certs
#  gather_facts: false
#  hosts: localhost
#  roles: 
#    - certs
#  tags: certs

- name: 3.install docker
  gather_facts: false
  hosts: k8s
  roles: 
    - docker
  tags: docker

