---
# This roles is executed on all nodes

- name: Modify hostname
  shell: hostnamectl set-hostname {{ hostname }}

- name: Turn off the firewalld
  service: name=firewalld state=stopped enabled=no 

#- name: Turn off the selinux
#  lineinfile: 
#    dest: /etc/selinux/config
#    regexp: "^SELINUX="
#    line: "SELINUX=disabled"

- name: Turn off the selinux
  selinux: 
    state: disabled

- name: Turn off the swap
  lineinfile: 
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: Immediate effect
  shell: swapoff -a

- name: Copy time zone
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: Address hosts
  template: src=hosts.j2 dest=/etc/hosts
